/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "phenixV1.h"


void
phenix_prog_1(char *host)
{
	CLIENT *clnt;
	struct utilisateur  *result_1;
	struct utilisateur  inscrire_1_arg;
	struct partenaire  *result_2;
	struct partenaire  creationpartenaire_1_arg;
	struct partenaire  *result_3;
	struct utilisateur  recherche_1_arg;
	struct commande  *result_4;
	struct detail_commande  achat_1_arg;
	struct note  *result_5;
	struct note  notation_1_arg;
	struct commande  *result_6;
	struct commande  annulation_1_arg;
	struct commande  *result_7;
	struct commande  reactivation_1_arg;
	void  *result_8;
	struct partenaire  historique_1_arg;
	struct commande  *result_9;
	int  fincommande_1_arg;
	bool_t  *result_10;
	struct utilisateur  supprimercompte_1_arg;
	struct partenaire  *result_11;
	struct partenaire  deletecomment_1_arg;
	struct partenaire  *result_12;
	struct partenaire  modificationcoordonnees_1_arg;
    int nb=0;
    struct utilisateur users[100];
    struct partenaire part[100];
    struct commande tab_com;
    struct article matrice_article[10][10]; 
   
   #ifndef	DEBUG
	clnt = clnt_create (host, PHENIX_PROG, SCENARIO_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    matrice_article[0][0].num=1;
    matrice_article[0][0].id_partenaire=1;
    strcpy(matrice_article[0][0].nom,"Chips");
    matrice_article[0][0].prix_unite=2;
    matrice_article[0][1].num=2;
    matrice_article[0][1].id_partenaire=1;
    strcpy(matrice_article[0][1].nom,"Saucisson");
    matrice_article[0][1].prix_unite=9;
    matrice_article[0][2].num=3;
    matrice_article[0][2].id_partenaire=1;
    strcpy(matrice_article[0][2].nom,"Pain");
    matrice_article[0][2].prix_unite=8;
    matrice_article[0][3].num=4;
    matrice_article[0][3].id_partenaire=1;
    strcpy(matrice_article[0][3].nom,"Brocoli");
    matrice_article[0][3].prix_unite=10;

    matrice_article[1][0].num=1;
    matrice_article[1][0].id_partenaire=2;
    strcpy(matrice_article[1][0].nom,"Coca");
    matrice_article[1][0].prix_unite=4;
    matrice_article[1][1].num=2;
    matrice_article[1][1].id_partenaire=2;
    strcpy(matrice_article[1][1].nom,"Oasis");
    matrice_article[1][1].prix_unite=2;
    matrice_article[1][2].num=3;
    matrice_article[1][2].id_partenaire=2;
    strcpy(matrice_article[1][2].nom,"Grenadine");
    matrice_article[1][2].prix_unite=2;
    matrice_article[1][3].num=4;
    matrice_article[1][3].id_partenaire=2;
    strcpy(matrice_article[1][3].nom,"Vin blanc");
    matrice_article[1][3].prix_unite=11;

    matrice_article[2][0].num=1;
    matrice_article[2][0].id_partenaire=3;
    strcpy(matrice_article[2][0].nom,"Comté");
    matrice_article[2][0].prix_unite=11;
    matrice_article[2][1].num=2;
    matrice_article[2][1].id_partenaire=3;
    strcpy(matrice_article[2][1].nom,"Reblochon");
    matrice_article[2][1].prix_unite=8;
    matrice_article[2][2].num=3;
    matrice_article[2][2].id_partenaire=3;
    strcpy(matrice_article[2][2].nom,"Bri");
    matrice_article[2][2].prix_unite=10;
    matrice_article[2][3].num=4;
    matrice_article[2][3].id_partenaire=3;
    strcpy(matrice_article[2][3].nom,"Fourme d'Amber");
    matrice_article[2][3].prix_unite=16;

    matrice_article[3][0].num=1;
    matrice_article[3][0].id_partenaire=4;
    strcpy(matrice_article[3][0].nom,"Frites");
    matrice_article[3][0].prix_unite=1;
    matrice_article[3][1].num=2;
    matrice_article[3][1].id_partenaire=4;
    strcpy(matrice_article[3][1].nom,"Patate douce");
    matrice_article[3][1].prix_unite=15;
    matrice_article[3][2].num=3;
    matrice_article[3][2].id_partenaire=4;
    strcpy(matrice_article[3][2].nom,"Graine de tournesol");
    matrice_article[3][2].prix_unite=10;
    matrice_article[3][3].num=4;
    matrice_article[3][3].id_partenaire=4;
    strcpy(matrice_article[3][3].nom,"Galette de mais");
    matrice_article[3][3].prix_unite=5;

    /********************************CRéation de clients*********************************************/
    
    printf("--------------INSCRIPTION DES CLIENTS----------------------\n\n\n");
    strcpy(inscrire_1_arg.nom,"TOUPR"); 
    strcpy(inscrire_1_arg.prenom,"Alain"); 
    strcpy(inscrire_1_arg.adresse,"Brest"); 
    strcpy(inscrire_1_arg.mail,"jho@gmail.com");
	result_1= inscrire_1(&inscrire_1_arg, clnt);
    strcpy(users[nb].nom,result_1->nom);
    strcpy(users[nb].prenom,result_1->prenom);
    strcpy(users[nb].adresse,result_1->adresse);
    strcpy(users[nb].mail,result_1->mail);
    users[nb].etat_compte=result_1->etat_compte;
    nb=nb+1;
     strcpy(inscrire_1_arg.nom,"Mathis"); 
    strcpy(inscrire_1_arg.prenom,"Elowan"); 
    strcpy(inscrire_1_arg.adresse,"Nantes"); 
    strcpy(inscrire_1_arg.mail,"na@g.com");
	result_1= inscrire_1(&inscrire_1_arg, clnt);
    strcpy(users[nb].nom,result_1->nom);
    strcpy(users[nb].prenom,result_1->prenom);
    strcpy(users[nb].adresse,result_1->adresse);
    strcpy(users[nb].mail,result_1->mail);
    users[nb].etat_compte=result_1->etat_compte;
    nb=nb+1;
    strcpy(inscrire_1_arg.nom,"Tuff"); 
    strcpy(inscrire_1_arg.prenom,"Alain"); 
    strcpy(inscrire_1_arg.adresse,"Nantes"); 
    strcpy(inscrire_1_arg.mail,"tfa@hotmail.com");
	result_1= inscrire_1(&inscrire_1_arg, clnt);
    strcpy(users[nb].nom,result_1->nom);
    strcpy(users[nb].prenom,result_1->prenom);
    strcpy(users[nb].adresse,result_1->adresse);
    strcpy(users[nb].mail,result_1->mail);
    users[nb].etat_compte=result_1->etat_compte;
    nb=nb+1;   
    strcpy(inscrire_1_arg.nom,"Rochard"); 
    strcpy(inscrire_1_arg.prenom,"Johan"); 
    strcpy(inscrire_1_arg.adresse,"Brest"); 
    strcpy(inscrire_1_arg.mail,"jo@gmail.com");
	result_1= inscrire_1(&inscrire_1_arg, clnt);
    strcpy(users[nb].nom,result_1->nom);
    strcpy(users[nb].prenom,result_1->prenom);
    strcpy(users[nb].adresse,result_1->adresse);
    strcpy(users[nb].mail,result_1->mail);
    users[nb].etat_compte=result_1->etat_compte;
    nb=nb+1;
     strcpy(inscrire_1_arg.nom,"LIKEME"); 
    strcpy(inscrire_1_arg.prenom,"Yan Marcel"); 
    strcpy(inscrire_1_arg.adresse,"Brest"); 
    strcpy(inscrire_1_arg.mail,"yan@gmail");
	result_1= inscrire_1(&inscrire_1_arg, clnt);
    strcpy(users[nb].nom,result_1->nom);
    strcpy(users[nb].prenom,result_1->prenom);
    strcpy(users[nb].adresse,result_1->adresse);
    strcpy(users[nb].mail,result_1->mail);
    users[nb].etat_compte=result_1->etat_compte;
	   nb=nb+1;
	if (result_1 == (struct utilisateur *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    for(int i=0;i<nb;i++)
    {
     printf("\n nom : %s\n prenom : %s\n lieu : %s\n mail : %s\n",users[i].nom,users[i].prenom,users[i].adresse,users[i].mail);
    }

    int nb_users=nb;
    /**********************************************************/
    struct note matrice_note[10][10];
    struct detail_commande tab_detail_commande[100]; 
    tab_detail_commande[0].article[0]=matrice_article[0][0];
    tab_detail_commande[0].nb_arctile=1;
    struct commande tab_commande[100];
    int n=1;
    for(int j=0;j<4;j++)
    {
        tab_commande[j].num=n*5;
        tab_commande[j].prix=10+n;
        tab_commande[j].client=*(inscrire_1((users+j), clnt));
        n=n*5;
    }
        nb=0;


    /**********************************************************/
        struct note pointeur_defaut;
        printf("\n\n\n\n-----------------------LES PARTENAIRES CRééS et initiés-------------------------\n\n"); 
        strcpy(creationpartenaire_1_arg.nom,"L'affinage");
        strcpy(creationpartenaire_1_arg.secteur,"Industriel");
        strcpy(creationpartenaire_1_arg.lieu,"Brest");
        creationpartenaire_1_arg.notes=matrice_note[nb];
        result_2 = creationpartenaire_1(&creationpartenaire_1_arg, clnt);
        strcpy(part[nb].nom,result_2->nom);
        strcpy(part[nb].secteur,result_2->secteur);
        strcpy(part[nb].lieu,result_2->lieu);
        part[nb].notes=&pointeur_defaut; 
        // part[nb].notes=&matrice_note[0][0]; 
        nb=nb+1;
        strcpy(creationpartenaire_1_arg.nom,"L'Artisan Fromager");
        strcpy(creationpartenaire_1_arg.secteur,"Commerce");
        strcpy(creationpartenaire_1_arg.lieu,"Nantes");
        creationpartenaire_1_arg.notes=matrice_note[nb];
        result_2 = creationpartenaire_1(&creationpartenaire_1_arg, clnt);
        strcpy(part[nb].nom,result_2->nom);
        strcpy(part[nb].secteur,result_2->secteur);
        strcpy(part[nb].lieu,result_2->lieu);
        part[nb].notes=&pointeur_defaut; 
        // part[nb].notes=&matrice_note[1][0]; 
        nb=nb+1;
        strcpy(creationpartenaire_1_arg.nom,"L'Oracle");
        strcpy(creationpartenaire_1_arg.secteur,"Commerce");
        strcpy(creationpartenaire_1_arg.lieu,"Brest");
        creationpartenaire_1_arg.notes=matrice_note[nb];
        result_2 = creationpartenaire_1(&creationpartenaire_1_arg, clnt);
        strcpy(part[nb].nom,result_2->nom);
        strcpy(part[nb].secteur,result_2->secteur);
        strcpy(part[nb].lieu,result_2->lieu);
        part[nb].notes=&pointeur_defaut; 
        nb=nb+1;

        if (result_2 == (struct partenaire *) NULL) {
            clnt_perror (clnt, "call failed");
        }
        for (int a=0;a<nb;a++)
        {
            printf("\n\n---------------------PARTENAIRE ° : %d-----------------\n nom : %s\n secteur : %s\n lieu : %s\n",(a+1),part[a].nom,part[a].secteur,part[a].lieu);
            printf("\n                  ---------------Notes de ce partenaire------------------                    \n");
            if(part[a].notes==&pointeur_defaut)
            {
                printf("\n                    Aucune note pour le partenaire                                    \n");
            }
            else {
                for(int i=0;i<2;i++)
                {


                    printf("\n note/5 : %d Commentaire : %s \n",part[a].notes[i].note,part[a].notes[i].commentaire);
                }
            }
        }
        printf("\n\n\n\n\n------------------------RECHERCHE DE PARTENAIRES-----------------------------------\n"); 
        for(int d=0 ;d<nb_users; d++)
        {

            printf("\n\n\n --------Recherche avec l'utilisateur :\n") ;
            printf("\n nom : %s\n prenom : %s\n lieu : %s\n mail : %s\n",users[d].nom,users[d].prenom,users[d].adresse,users[d].mail);
            result_3 = recherche_1(&users[d], clnt);
            if (result_3 == (struct partenaire *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            int cpt=0;
            printf("\n Les partenaires couvrant la zone de  %s \n",(*result_3).lieu);
            for(int c=0; c<=nb; c++)
            {
                if((strcmp(part[c].lieu,(*result_3).lieu))==0)
                {    
                    printf("\n Partenaire n° %d  trouvé : \n",cpt+1);
                    printf("\n nom : %s\n secteur : %s\n lieu : %s\n",part[c].nom,part[c].secteur,part[c].lieu);
                    cpt=cpt+1;
                }

            }
            if(cpt==0)
                printf("\n0 Partenaire trouvé à %s \n",(*result_3).lieu);
        }

        printf("\n\n\n\n------------------ ACHAT PAR UN CLIENT ---------------\n\n"); 
        int p=0;
        for(int a=0; a<nb_users; a++)
        {
            if(a>1 && a<3)p=1;
            if(a>3)p=2;
            printf("\n\n\nArticles disponibles chez le partenaire d'ID : %d ( %s ) \n",2,part[p].nom);
            int indices_articles[2][10];
            int compte_indices=0;
            for (int e=0; e<4; e++)
            {
                for(int f=0; f<4; f++) 
                {
                    
                    if(matrice_article[e][f].id_partenaire==(p+1))
                    {
                        printf("\n Nom : %s\n Prix unitaire : %dEuros\n Numéro : %d\n",matrice_article[e][f].nom, matrice_article[e][f].prix_unite,matrice_article[e][f].num);
                        indices_articles[0][compte_indices]=e; 
                        indices_articles[1][compte_indices]=f; 
                        compte_indices=compte_indices+1;
                    }
                }


            }
            if(strcmp(users[a].adresse,part[a].lieu))
            {
            printf("\n------------------Articles selectionnés par le client--------------\n"); 
            int g;
            for(g=0 ; g<compte_indices; g++)
            {
                tab_detail_commande[a].article[g]=matrice_article[indices_articles[0][g]][indices_articles[1][g]];
                printf("\n Nom : %s\n",tab_detail_commande[a].article[g].nom);
            }
            tab_detail_commande[a].nb_arctile=2*g;
            int somme=0;
            for(int h=0; h<g; h++)
            {
                somme=somme+tab_detail_commande[a].article[h].prix_unite; 

            }
            somme=tab_detail_commande[a].nb_arctile*somme; 
            printf("\n Nombre d'articles de la commande :%d\n Prix total de la commande : %.2fEuros\n",tab_detail_commande[a].nb_arctile,(double)somme/10); 
            tab_commande[a].num=a;
            tab_commande[a].prix=(double)somme/10;
            tab_commande[a].client=*(inscrire_1((users+a), clnt));
            result_4 = achat_1(&tab_detail_commande[a], clnt);
            if (result_4 == (struct commande *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            tab_commande[a].detail=result_4->detail; 
            tab_commande[a].etat_commande=result_4->etat_commande;
            printf("\n\nRésumé de la commande de : Mr/Mme  %s\n",users[a].nom); 
            printf("\n Commande n° :%d\n Total de la somme : %.2fEuros\n Statue Coammnde (1  =  En cours / 0 =  Annulée) : %d\n",tab_commande[a].num,(double)tab_commande[a].prix,tab_commande[a].etat_commande);
            }
            else 
            {
                printf("\n!!ACHAT IMPOSSIBLE \nle Partenaire  %s ne couvre pas la zone de l'utilisateur %s\nLe client doit essayer un autre partenaire\n\n\n",part[a].nom,users[a].nom);
                tab_commande[a].num=999;
            }

        }
        printf("\n\n\n\n-------------------------------  NOTATION DE COMMANDE -------------------------------------\n\n\n");

        struct note note_temporaire; 

        strcpy(note_temporaire.commentaire,"Produit acceptable..."); 
        note_temporaire.note=5; 
        note_temporaire.commande_note=tab_commande[0];
        result_5 = notation_1(&note_temporaire, clnt);
        if (result_5 == (struct note *) NULL) {
            clnt_perror (clnt, "call failed");
        }	
        matrice_note [0][0].note=result_5->note;
        strcpy(matrice_note[0][0].commentaire,(*result_5).commentaire); 
        matrice_note[0][0].commande_note=result_5->commande_note;

        strcpy(note_temporaire.commentaire,"Produit pas terrible..."); 
        note_temporaire.note=3; 
        note_temporaire.commande_note=tab_commande[1];
        result_5 = notation_1(&note_temporaire, clnt);
        if (result_5 == (struct note *) NULL) {
            clnt_perror (clnt, "call failed");
        }	
        matrice_note [0][1].note=result_5->note;
        strcpy(matrice_note[0][1].commentaire,(*result_5).commentaire); 
        matrice_note[0][1].commande_note=result_5->commande_note;

        strcpy(note_temporaire.commentaire,"Je m'attendais à mieux..."); 
        note_temporaire.note=1; 
        note_temporaire.commande_note=tab_commande[2];
        result_5 = notation_1(&note_temporaire, clnt);
        if (result_5 == (struct note *) NULL) {
            clnt_perror (clnt, "call failed");
        }	
        matrice_note [1][0].note=result_5->note;
        strcpy(matrice_note[1][0].commentaire,(*result_5).commentaire); 
        matrice_note[1][0].commande_note=result_5->commande_note;

        strcpy(note_temporaire.commentaire,"Le pain est racis"); 
        note_temporaire.note=2; 
        note_temporaire.commande_note=tab_commande[3];
        result_5 = notation_1(&note_temporaire, clnt);
        if (result_5 == (struct note *) NULL) {
            clnt_perror (clnt, "call failed");
        }	
        matrice_note [1][1].note=result_5->note;
        strcpy(matrice_note[1][1].commentaire,(*result_5).commentaire); 
        matrice_note[1][1].commande_note=result_5->commande_note;

        strcpy(note_temporaire.commentaire,"Vraiment Incroyable ! je recommande !"); 
        note_temporaire.note=5; 
        note_temporaire.commande_note=tab_commande[4];
        result_5 = notation_1(&note_temporaire, clnt);
        if (result_5 == (struct note *) NULL) {
            clnt_perror (clnt, "call failed");
        }	
        matrice_note [2][0].note=result_5->note;
        strcpy(matrice_note[2][0].commentaire,(*result_5).commentaire); 
        matrice_note[2][0].commande_note=result_5->commande_note;
         tab_commande[5].num=999;
        strcpy(note_temporaire.commentaire,"Vraiment Incroyable ! je recommande !"); 
        note_temporaire.note=5; 
        note_temporaire.commande_note=tab_commande[5];
        result_5 = notation_1(&note_temporaire, clnt);
        if (result_5 == (struct note *) NULL) {
            clnt_perror (clnt, "call failed");
        }	
        matrice_note [2][1].note=result_5->note;
        strcpy(matrice_note[2][1].commentaire,(*result_5).commentaire); 
        matrice_note[2][1].commande_note=result_5->commande_note;
 

     

        printf("\n\n\n\n--------------Les NOTES Ajoutées ---------------------------\n"); 

        for(int j=0; j<3;j++)
        {

            for(int i=0; i<2;i++)
            {
                if(matrice_note[j][i].commande_note.num==999)
                {

                }
                else{

                printf("\nNom du client : %s --- Numéro de la commande : %d \n",matrice_note[j][i].commande_note.client.nom,matrice_note[j][i].commande_note.num);
                printf("\nNote (sur 5) : %d, Commentaire (éventuel) : %s\n",matrice_note[j][i].note,matrice_note[j][i].commentaire);
                printf("\n");
                }
            }



        } 
        printf("\n\n\n\n --------------- ANNULATION D'UNE COMMANDE  -------------------------\n\n");
        printf("\n ---- État des commandes --------\n");
        for(int i=0; i<5; i++)

        {


            if(tab_commande[i].num!=999)
            {
                if(tab_commande[i].etat_commande==1)
                {
                    printf("N° commande : %d  Client : Mr %s (commande en cours)\n",tab_commande[i].num,tab_commande[i].client.nom); 

                }
                else
                {
                     printf("N° commande : %d  Client : Mr %s (Annulée/désactivée)\n",tab_commande[i].num,tab_commande[i].client.nom);
                }

            }

        }
        printf("\n\n Commande N° %d à annuler\n",tab_commande[2].num);
        

        result_6 = annulation_1(&tab_commande[2], clnt);

        if (result_6 == (struct commande *) NULL) {
            clnt_perror (clnt, "call failed");
        }
        printf("\n--- Nouvel état des commandes -----\n");
        tab_commande[2]=(*result_6);

        for(int i=0; i<5; i++)

        {


            if(tab_commande[i].num!=999)
            {
                if(tab_commande[i].etat_commande==1)
                {
                    printf("N° commande : %d  Client : Mr %s (commande en cours)\n",tab_commande[i].num,tab_commande[i].client.nom); 

                }
                else
                {
                     printf("N° commande : %d  Client : Mr %s (Annulée/désactivée)\n",tab_commande[i].num,tab_commande[i].client.nom);
                }

            }

        } 
        printf("\n\n Commande N° %d à annuler\n",tab_commande[3].num);
        

        result_6 = annulation_1(&tab_commande[3], clnt);

        if (result_6 == (struct commande *) NULL) {
            clnt_perror (clnt, "call failed");
        }
        printf("\n--- Nouvel état des commandes -----\n");
        tab_commande[3]=(*result_6);

        for(int i=0; i<5; i++)

        {


            if(tab_commande[i].num!=999)
            {
                if(tab_commande[i].etat_commande==1)
                {
                    printf("N° commande : %d  Client : Mr %s (commande en cours)\n",tab_commande[i].num,tab_commande[i].client.nom); 

                }
                else
                {
                     printf("N° commande : %d  Client : Mr %s (Annulée/désactivée)\n",tab_commande[i].num,tab_commande[i].client.nom);
                }

            }

        }


        printf("\n\n\n\n --------------- RÉACTIVATIION  D'UNE COMMANDE  -------------------------\n\n");
        printf("\n ---- État des commandes --------\n");
        for(int i=0; i<5; i++)

        {


            if(tab_commande[i].num!=999)
            {
                if(tab_commande[i].etat_commande==1)
                {
                    printf("N° commande : %d  Client : Mr %s (commande en cours)\n",tab_commande[i].num,tab_commande[i].client.nom); 

                }
                else if(tab_commande[i].etat_commande==2)
                {
                     printf("N° commande : %d  Client : Mr %s (commande réactivée en cours)\n",tab_commande[i].num,tab_commande[i].client.nom);
                }
                else {

                     printf("N° commande : %d  Client : Mr %s (Annulée/désactivée)\n",tab_commande[i].num,tab_commande[i].client.nom);
                }

            }

        }
        printf("\n\n Commande N° %d à réactiver\n",tab_commande[3].num);
        

        result_7 = reactivation_1(&(tab_commande[3]), clnt);

        if (result_7 == (struct commande *) NULL) {
            clnt_perror (clnt, "call failed");
        }        printf("\n--- Nouvel état des commandes -----\n");

        tab_commande[3]=(*result_7);

        for(int i=0; i<5; i++)

        {


            if(tab_commande[i].num!=999)
            {
                if(tab_commande[i].etat_commande==1)
                {
                    printf("N° commande : %d  Client : Mr %s (commande en cours)\n",tab_commande[i].num,tab_commande[i].client.nom); 

                }
                else if(tab_commande[i].etat_commande==2)
                {
                     printf("N° commande : %d  Client : Mr %s (commande réactivée en cours)\n",tab_commande[i].num,tab_commande[i].client.nom);
                }
                else {

                     printf("N° commande : %d  Client : Mr %s (Annulée/désactivée)\n",tab_commande[i].num,tab_commande[i].client.nom);
                }

            }

        }

        result_8 = historique_1(&historique_1_arg, clnt);
        if (result_8 == (void *) NULL) {
            clnt_perror (clnt, "call failed");
        }
        result_9 = fincommande_1(&fincommande_1_arg, clnt);
        if (result_9 == (struct commande *) NULL) {
            clnt_perror (clnt, "call failed");
        }
        result_10 = supprimercompte_1(&supprimercompte_1_arg, clnt);
        if (result_10 == (bool_t *) NULL) {
            clnt_perror (clnt, "call failed");
        }
        result_11 = deletecomment_1(&deletecomment_1_arg, clnt);
        if (result_11 == (struct partenaire *) NULL) {
            clnt_perror (clnt, "call failed");
        }
        result_12 = modificationcoordonnees_1(&modificationcoordonnees_1_arg, clnt);
        if (result_12 == (struct partenaire *) NULL) {
            clnt_perror (clnt, "call failed");
        }
#ifndef	DEBUG
        clnt_destroy (clnt);
#endif	 /* DEBUG */
}


    int
main (int argc, char *argv[])
{
    char *host;

    if (argc < 2) {
        printf ("usage: %s server_host\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    phenix_prog_1 (host);
    exit (0);
}
