/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "phenixV1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
phenix_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct utilisateur inscrire_1_arg;
		struct partenaire creationpartenaire_1_arg;
		struct utilisateur recherche_1_arg;
		struct detail_commande achat_1_arg;
		struct note notation_1_arg;
		struct commande annulation_1_arg;
		struct commande reactivation_1_arg;
		struct partenaire historique_1_arg;
		int fincommande_1_arg;
		struct utilisateur supprimercompte_1_arg;
		struct partenaire deletecomment_1_arg;
		struct partenaire modificationcoordonnees_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INSCRIRE:
		_xdr_argument = (xdrproc_t) xdr_utilisateur;
		_xdr_result = (xdrproc_t) xdr_utilisateur;
		local = (char *(*)(char *, struct svc_req *)) inscrire_1_svc;
		break;

	case CREATIONPARTENAIRE:
		_xdr_argument = (xdrproc_t) xdr_partenaire;
		_xdr_result = (xdrproc_t) xdr_partenaire;
		local = (char *(*)(char *, struct svc_req *)) creationpartenaire_1_svc;
		break;

	case RECHERCHE:
		_xdr_argument = (xdrproc_t) xdr_utilisateur;
		_xdr_result = (xdrproc_t) xdr_partenaire;
		local = (char *(*)(char *, struct svc_req *)) recherche_1_svc;
		break;

	case ACHAT:
		_xdr_argument = (xdrproc_t) xdr_detail_commande;
		_xdr_result = (xdrproc_t) xdr_commande;
		local = (char *(*)(char *, struct svc_req *)) achat_1_svc;
		break;

	case NOTATION:
		_xdr_argument = (xdrproc_t) xdr_note;
		_xdr_result = (xdrproc_t) xdr_note;
		local = (char *(*)(char *, struct svc_req *)) notation_1_svc;
		break;

	case ANNULATION:
		_xdr_argument = (xdrproc_t) xdr_commande;
		_xdr_result = (xdrproc_t) xdr_commande;
		local = (char *(*)(char *, struct svc_req *)) annulation_1_svc;
		break;

	case REACTIVATION:
		_xdr_argument = (xdrproc_t) xdr_commande;
		_xdr_result = (xdrproc_t) xdr_commande;
		local = (char *(*)(char *, struct svc_req *)) reactivation_1_svc;
		break;

	case HISTORIQUE:
		_xdr_argument = (xdrproc_t) xdr_partenaire;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) historique_1_svc;
		break;

	case FINCOMMANDE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_commande;
		local = (char *(*)(char *, struct svc_req *)) fincommande_1_svc;
		break;

	case SUPPRIMERCOMPTE:
		_xdr_argument = (xdrproc_t) xdr_utilisateur;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) supprimercompte_1_svc;
		break;

	case DELETECOMMENT:
		_xdr_argument = (xdrproc_t) xdr_partenaire;
		_xdr_result = (xdrproc_t) xdr_partenaire;
		local = (char *(*)(char *, struct svc_req *)) deletecomment_1_svc;
		break;

	case MODIFICATIONCOORDONNEES:
		_xdr_argument = (xdrproc_t) xdr_partenaire;
		_xdr_result = (xdrproc_t) xdr_partenaire;
		local = (char *(*)(char *, struct svc_req *)) modificationcoordonnees_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PHENIX_PROG, SCENARIO_1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PHENIX_PROG, SCENARIO_1, phenix_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PHENIX_PROG, SCENARIO_1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PHENIX_PROG, SCENARIO_1, phenix_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PHENIX_PROG, SCENARIO_1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
