/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "phenixV1.h"

bool_t
xdr_partenaire (XDR *xdrs, partenaire *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->lieu, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secteur, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->notes, sizeof (struct note), (xdrproc_t) xdr_note))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_utilisateur (XDR *xdrs, utilisateur *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->adresse, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mail, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->etat_compte))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_article (XDR *xdrs, article *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_partenaire))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix_unite))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_detail_commande (XDR *xdrs, detail_commande *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->article, 20,
		sizeof (article), (xdrproc_t) xdr_article))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_arctile))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_commande (XDR *xdrs, commande *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_utilisateur (xdrs, &objp->client))
		 return FALSE;
	 if (!xdr_detail_commande (xdrs, &objp->detail))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->etat_commande))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_note (XDR *xdrs, note *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->note))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->commentaire, 500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_commande (xdrs, &objp->commande_note))
		 return FALSE;
	return TRUE;
}
